# Generated by Django 4.1.5 on 2023-02-03 03:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driver_license',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='plate_number',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='user_group',
            field=models.CharField(choices=[('Passenger', 'PASSENGER'), ('Driver', 'DRIVER'), ('Manager', 'MANAGER')], default='Passenger', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Null', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Female', 'FEMALE'), ('Male', 'MALE'), ('Others', 'OTHERS'), ('Hope not to say', 'UNKNOWN')], default='Female', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Null', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='Null', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Null', max_length=64),
        ),
    ]
