# Generated by Django 4.1.5 on 2023-02-03 03:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_user_driver_license_user_plate_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+19001234567', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='plate_number',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
